### PR TITLE
Removed commons-io

### PR DESCRIPTION
**Pull request by satsen**
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/develop/docs/notes.md

Note: I made sure to only use JDK 7 and Scala 2.11 methods

### CODE REVIEW

**Comment by satsen** [comment]
I also tried to remove `cats` since it's only used 3 times and in one class only (JsonCodecs), but the strange Scala syntax is just beyond me. After hours I made up something but I don't even know if it will function the same, so if anybody can get rid of `cats`, that would be great.

**Comment by aslesarenko** [comment]
@satsen, please fix compilation

**Comment by satsen** [comment]
@aslesarenko That is code that I did not touch. My Scala knowledge is not enough to fix errors I did not cause, perhaps github uses wrong scala, i don't know.

**Comment by aslesarenko** [comment]
You removed dependency and some other code doesn't compile even though you don't touch it.

**Pull request closed without merging**
