### PR TITLE
Add optional default value to `ByIndex`

### LINKED ISSUE #99: ByIndex problems
- [x] index should not be Scala Int. `Value[SInt.type]` expected
- [ ] default value may me useful

relates to #87, #88, #98

### PR DESCRIPTION
**Pull request by greenhat**
Replaced by #167
Closes #99
Todo:
- [ ] check/confirm that default value is evaluated;

### CODE REVIEW

**Comment by greenhat** [comment]
@kushti @catena2w I've with passing default value as a second parameter (see [previous thoughts](https://github.com/ScorexFoundation/sigmastate-interpreter/issues/99#issuecomment-388035036)) 

Here is a couple of usage examples:
`Array(1, 2)(3, 0) == 0`
`OUTPUTS.map(fun (box: Box) = box.value)(3, 0)== 0`

**Comment by ergomorphic** [comment]
@greenhat @catena2w I don't like the idea of having such syntax `Array(1, 2)(3, 0) == 0`.
This makes syntax unreadable.

**Comment by greenhat** [comment]
@ergomorphic Agreed. Let's go with `getOrElse(index, default)`

**Comment by greenhat** [comment]
Continued in #167

**Pull request closed without merging**
