### PR TITLE
[6.0] Global.serialize method

### PR DESCRIPTION
**Pull request by aslesarenko**
In this PR:
- Global.serialize method is added
- global operation serialize() is added and translated to Global.serializer method call
- Global.serialize is properly compiled to ErgoTree (tests added)
- SMethod.explicitTypeArgs added to support serialization of necessary types as part of MethodCall serialization, which cannot be inferred from the MethodCall itself.

### CODE REVIEW

**Review by kushti — CHANGES_REQUESTED** [review]
There are not enough tests:
* do (de)serialization test for the new methods call in MethodCallSerializerSpecification
* do serialize - deserialize roundtrip test 
* test newly supported data types , namely Header and Option[], explicitly , but better to test more , see BasicOpsSpecification  in deserialize PR

**Comment by aslesarenko** [comment]
> * do serialize - deserialize roundtrip test
> 
> * test newly supported data types , namely Header and Option[], explicitly , but better to test more , see BasicOpsSpecification  in deserialize PR

Do you suggest to base this PR on top of #979?

**Comment by kushti** [comment]
> > * do serialize - deserialize roundtrip test
> > * test newly supported data types , namely Header and Option[], explicitly , but better to test more , see BasicOpsSpecification  in deserialize PR
> 
> Do you suggest to base this PR on top of #979?

Sure, how else can you check the roundtrip . Also, new serializers (Header & Option) are there

**Comment by aslesarenko** [comment]
> > Do you suggest to base this PR on top of #979?
> 
> Sure, how else can you check the roundtrip . Also, new serializers (Header & Option) are there

Ok, then this can be postponed until:
- #987 is merged
- #979 is finalized and merged

**Comment by kushti** [comment]
> > > Do you suggest to base this PR on top of #979?
> > 
> > 
> > Sure, how else can you check the roundtrip . Also, new serializers (Header & Option) are there
> 
> Ok, then this can be postponed until:
> 
>     * [[6.0] Merge with refactored SigmaCompiler #987](https://github.com/ScorexFoundation/sigmastate-interpreter/pull/987) is merged
> 
>     * [[6.0] Global.deserializeTo[] method #979](https://github.com/ScorexFoundation/sigmastate-interpreter/pull/979) is finalized and merged

There is no need to wait for merge of #979. Actually, this PR and #979 will be likely merged about the same time.

**Comment by aslesarenko** [comment]
> There is no need to wait for merge of #979. Actually, this PR and #979 will be likely merged about the same time.

At least tests should be fixed in #979 before I can merge it into this PR.

**Comment by kushti** [comment]
TODO: 
* check and incorporate changes from https://github.com/ScorexFoundation/sigmastate-interpreter/pull/995
* check if a specific serializer w. costing possible / makes sense

**Comment by aslesarenko** [comment]
> * check if a specific serializer w. costing possible / makes sense

Please clarify:
- Which specific serializer? 
- what "possible / makes sense" means?

**Comment by kushti** [comment]
@ergomorphic those are notes for me, the PR is not finished, please review finished PRs instead

**Comment by aslesarenko** [comment]
@kushti, LGTM, cannot approve my own PR, consider approved.

**Review by kushti — APPROVED** [review]

**Pull request merged**
